# Site settings
title: Blog
subtitle: My work on the Web
author: David Palacios
email: davidpalrdz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About coding and open source projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davidpalacios.github.io/" # the base hostname & protocol for your site
github_username:  davidpalacios

# Build settings
markdown: kramdown
highlighter: rouge
